# Generated by Django 5.2.4 on 2025-07-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_alter_badge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
