# Generated by Django 5.2.4 on 2025-07-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0003_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='do_again',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objective',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='objective',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objective',
            name='thoughts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='with_who',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
