# Generated by Django 5.2.4 on 2025-07-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0004_objective_date_objective_do_again_objective_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='memory_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='objective',
            name='with_whom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cu cine'),
        ),
        migrations.AddField(
            model_name='objective',
            name='would_repeat',
            field=models.BooleanField(default=False, verbose_name='Ai repeta experiența?'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Locația'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Evaluare (1-10)'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='thoughts',
            field=models.TextField(blank=True, null=True, verbose_name='Gânduri și amintiri'),
        ),
    ]
