# Generated by Django 5.2.4 on 2025-07-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0005_objective_memory_date_objective_with_whom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='with_whom',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='would_repeat',
        ),
        migrations.AddField(
            model_name='objective',
            name='memory_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='objective',
            name='memory_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='memory_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objective',
            name='memory_thoughts',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='objective',
            name='memory_with',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='objective',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='objective',
            name='memory_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='objective',
            name='thoughts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
